### ISSUE TITLE
Feature Request: add example using clingo-dl through Python API 

### ISSUE THREAD

**Issue by chenkins** [potassco/clingo-dl#22]
@MaxOstrowski and @wanko pointed me out to https://github.com/potassco/tefoli/blob/master/theory.py. They also informed me that import dl method in https://www.cs.uni-potsdam.de/~torsten/hybris.pdf is outdated.

Feature request: add theory.py as submodule here and make an example how to run a model via Python API.

**Comment by rkaminsk** [comment]
I don't think, it makes sense to have it as a submodule. We could add a link in the readme to the tefoli project though.

**Comment by MaxOstrowski** [comment]
Outdated, example is in the wip branch.

**Comment by rkaminsk** [comment]
> Outdated, example is in the wip branch.

We actually have to remove that line from the README again. Tefoli is no longer needed and clingo-dl comes with a python module out-of-the-box.
