### ISSUE TITLE
Measured times seem to be of

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingo-dl#23]
Having a solving time of 200s and a propagation time in thread 1 of 230s.

```
Models       : 2
  Optimum    : yes
Optimization : 5
Calls        : 1
Time         : 471.422s (Solving: 199.78s 1st Model: 198.34s Unsat: 0.28s)
CPU Time     : 670.732s
Threads      : 2        (Winner: 0)

Choices      : 11171912 (Domain: 3813027)
Conflicts    : 16       (Analyzed: 10)
Restarts     : 0       
Model-Level  : 100488.5
Problems     : 7        (Average Length: 0.29 Splits: 0)
Lemmas       : 6650     (Deleted: 0)
  Binary     : 1402     (Ratio:  21.08%)
  Ternary    : 421      (Ratio:   6.33%)
  Conflict   : 10       (Average Length:    3.2 Ratio:   0.15%) 
  Loop       : 0        (Average Length:    0.0 Ratio:   0.00%) 
  Other      : 6640     (Average Length:    1.4 Ratio:  99.85%) 
  Distributed: 1414     (Ratio: 14140.00% Average LBD: 126.12) 
  Integrated : 1414     (Ratio: 100.00% Unit: 70 Average Jumps: 300.07)
Backjumps    : 10       (Average: 12.70 Max:  43 Sum:    127)
  Executed   : 9        (Average: 12.60 Max:  43 Sum:    126 Ratio:  99.21%)
  Bounded    : 1        (Average:  1.00 Max:   1 Sum:      1 Ratio:   0.79%)

Rules        : 25906842
  Choice     : 314245  
  Minimize   : 1       
  Heuristic  : 84924   
Atoms        : 24953479
Bodies       : 1395372 
  Count      : 15      
Equivalences : 3453778  (Atom=Atom: 852176 Body=Body: 147427 Other: 2454175)
Tight        : Yes
Variables    : 346719   (Eliminated:    0 Frozen: 346719)
Constraints  : 698510   (Binary:  72.3% Ternary:  27.4% Other:   0.3%)

DifferenceLogic
  Time init(s): 3.95669
  Mutexes    : 0
  [Thread 0]
    Propagation(s): 230.995
    Dijkstra(s): 0
    Undo(s)  : 10.5192
    True edges: 0
    False edges: 0
    False edges (inverse): 1.80513e+07
    False edges (partial): 47798
    False edges (partial+): 0
    Edges added: 2.97805e+07
    Edges skipped: 2.93673e+07
    Edges propagated: 0
    Cost consistency: 7.19706e+07
    Cost forward: 0
    Cost backward: 0
  [Thread 1]
    Propagation(s): 165.12
    Dijkstra(s): 0
    Undo(s)  : 4.53704
    True edges: 0
    False edges: 0
    False edges (inverse): 703899
    False edges (partial): 609
    False edges (partial+): 0
    Edges added: 3.30927e+07
    Edges skipped: 3.24678e+07
    Edges propagated: 0
    Cost consistency: 1.96688e+08
    Cost forward: 0
    Cost backward: 0
```

**Comment by rkaminsk** [comment]
I do not think that there is a bug. I think propagate is called during initial simplification, which is not included in the solving time. This also explain why thread 0 (the master) spends more time propagating.

**Comment by MaxOstrowski** [comment]
But initial simplification takes place outside of the propagators init function ?
As this is only `Time init(s): 3.95669`.



Btw: any idea about #choices/#conflicts ? We only have 5% of the choices when disabling --propagate=partial
Is it possible that partial assignments are unit on a lower dl ?

**Comment by rkaminsk** [comment]
> But initial simplification takes place outside of the propagators init function ?
> As this is only `Time init(s): 3.95669`.

No propagation happens in init. I only implemented it like this in the clingcon prototype.

> Btw: any idea about #choices/#conflicts ? We only have 5% of the choices when disabling --propagate=partial

I noticed this behavior with clingo-dl before. I do not know what to do about it.

> Is it possible that partial assignments are unit on a lower dl ?

I really do not know. I do not know how this would be reflected in the statistics. I would think it should still count as a backjump; but maybe it does not.

In general, the propagator just detects conflicts. So it can always happen that a conflict is immediately asserting on a lower level without any conflict resolution. I have the feeling that this is what happens and that it is reinforced when propagation is enabled. I do not know why. You could add a custom statistics for it by examining the reason clause (all but one literal are on lower levels).

**Comment by MaxOstrowski** [comment]
> No propagation happens in init. I only implemented it like this in the clingcon prototype.
This means that the 199s are plain solving time and 471.422s (Total time) - 199s are grounding + preprocessing. Maybe it would be worth thinking about giving an extra stats output for grounding time (in general in clingo)? Otherwise there is currently no way to distinguish if the grounding or the preprocessing took all your time.

**Comment by rkaminsk** [comment]
It has been like this for a long time. Since the statistics output is hard to fine-tune, it is something I won't touch myself. Also this might be something that would better be done in clasp by providing reading/preprocessing time so that clingo does not have to be touched. You can open a PR but I would not accept anything that messes up the `--stats` output; it has to look nice.

If you need the figures in you experiments, you could measure the time in clingo-dl.

**Comment by MaxOstrowski** [comment]
Thanks for the idea.

Sorry for going a bit off topic here, i collected some statistics.
On this example I hacked into the add_edge_atom function of clingo-dl to count the clauses/conflicts etc...
99.997% of all clauses (13 million in this example) are already satisfied (contain a true literal).
Otherwise, we have around 750 conflicting clauses (all lits false) which are not reflected in the stats, and around 60 of them contain only one literal on the current dl.

Furthermore we have around 5000 clauses where exactly one literal is not yet decided.
Does this information help to speed up the --propagate=partial "algorithm", maybe stopping on already true edges etc. to avoid the massive number of already true clauses?

**Comment by rkaminsk** [comment]
Sounds strange. Function `add_edge` should only add a clause that also causes a conflict. Maybe the partial propagation adds unnecessary clauses, which should be avoided.

**Comment by MaxOstrowski** [comment]
Sorry, i have written the wrong function (git diff fooled me) and edited it silently.
It is of course in the do_propagate function!

**Comment by rkaminsk** [comment]
If any of the propagation modes add SAT clauses, then those can/should be skipped.

**Comment by MaxOstrowski** [comment]
They do if I've measured things right.
The question is, can you avoid the computation of those beforehand ;)

**Comment by rkaminsk** [comment]
I don't think it is the cost of computing them but the fact that they confuse the solver. add_edge cannot be made faster (easily). And partial propagation does not cost much extra. We just have to skip constraints that harm the search.

**Comment by MaxOstrowski** [comment]
I opened a PR that avoids satisfied clauses.

I also checked again the added clauses, and they were all of the form:
`a-0 <= k AND neg 0-a <=-k-1`
and additionally
`a-0 <= k AND neg 0-a <=-l` where `l > k`
Most inferences are binary and decided on the same level (due to the ASP encoding that does this manually).

Otherwise I observed very long clauses containing ~ 50 literals (-1) (false on root level).
Maybe this information helps somehow.

**Comment by MaxOstrowski** [comment]
BTW: We still haven't found out why the conflicts are not counted in the statistics. Still want to investigate this.

**Comment by rkaminsk** [comment]
> I opened a PR that avoids satisfied clauses.

Does it help? Do we get less choices?

> Otherwise I observed very long clauses containing ~ 50 literals (-1) (false on root level).

This can happen because even though edges are associated with facts we still do not know how they will contribute to the potential. I don't think that they can be removed in general but in some cases it might be possible.

**Comment by rkaminsk** [comment]
> BTW: We still haven't found out why the conflicts are not counted in the statistics. Still want to investigate this.

You could also ask Benjamin under which conditions conflicts are counted. Have you looked at the decision levels? You should also count how many literals are false on the current decision level. Maybe a clause is not counted as conflict if there is only one literal on the current decision level.

**Comment by MaxOstrowski** [comment]
> Does it help? Do we get less choices?
No, but it "seems" a bit faster ;-)
Closing this for now.

**Comment by rkaminsk** [comment]
I think we should investigate one more thing. In our clingcon prototype I noticed that it is bad to add clauses that force the solver to assert a literal on a previous decision level because this can lead to excessive backtracking increasing the choices. I would still like to check the following:

- How many of the unit resulting clauses are forcing the solver to backtrack, i.e., all decided literals are on a lower level than the current decision level? This should be clauses among the 5000 clauses you mentioned above. If there are such clauses, maybe we should skip them too.

**Comment by MaxOstrowski** [comment]
Rechecked, none of the unit clauses are asserting on a lower lower, all unit clauses have at least one decided literal on the current dl.

**Comment by MaxOstrowski** [comment]
> 
> 
> >    But initial simplification takes place outside of the propagators init function ?
> >    As this is only Time init(s): 3.95669.
> 
> No propagation happens in init. I only implemented it like this in the clingcon prototype.

The timing is still off and I can't explain it.
Your current guess is that this is initial propagation (not done in init but afterwards on level 0).

I ran into the following using clingo-dl conda dev:
`clingo-dl encoding/version_default.lp -t2 tempcheck -q2,0 --stats=3 --heuristic=Domain --propagate=partial --lookahead=no`

```
Models       : 2
  Optimum    : yes
Optimization : 3240046
Calls        : 1
Time         : 242.575s (Solving: 112.01s 1st Model: 111.15s Unsat: 0.28s)
CPU Time     : 354.432s
...
DifferenceLogic
  Time init(s): 2.68728
  Mutexes    : 0
  [Thread 0]
    Propagation(s): 127.941
    Dijkstra(s): 0
    Undo(s)  : 2.83137
    True edges: 0
    False edges: 0
    False edges (inverse): 6.98495e+06
    False edges (partial): 78337
    False edges (partial+): 0
    Edges added: 1.15576e+07
    Edges skipped: 1.11571e+07
    Edges propagated: 0
    Cost consistency: 5.5567e+07
    Cost forward: 0
    Cost backward: 0
  [Thread 1]
    Propagation(s): 88.6952
    Dijkstra(s): 0
    Undo(s)  : 3.72276
```


Same call with additionally `--solve-limit=1` to more or less see how much time is spend during initial propagation:
```
Models       : 0+
Calls        : 1
Time         : 154.714s (Solving: 27.53s 1st Model: 0.00s Unsat: 0.00s)
CPU Time     : 154.704s
Threads      : 2        (Winner: 0)

Choices      : 1       
Conflicts    : 1        (Analyzed: 1)
Restarts     : 0       
Problems     : 1        (Average Length: 1.00 Splits: 0)
Lemmas       : 2550     (Deleted: 0)
...
DifferenceLogic
  Time init(s): 2.60475
  Mutexes    : 0
  [Thread 0]
    Propagation(s): 26.9653
    Dijkstra(s): 0
    Undo(s)  : 0
    True edges: 0
    False edges: 0
    False edges (inverse): 2681
    False edges (partial): 0
    False edges (partial+): 0
    Edges added: 337417
    Edges skipped: 70660
    Edges propagated: 0
    Cost consistency: 398720
    Cost forward: 0
    Cost backward: 0
  [Thread 1]
    Propagation(s): 27.4302
    Dijkstra(s): 0
    Undo(s)  : 0
```

Here the time propagation and init matches the total solving time. And all preprocessing should have been done until the first conflict occured. So how to explain 

> Solving: 112.01s

vs
> Propagation(s): 127.941

**Comment by rkaminsk** [comment]
> So how to explain `Solving: 112.01s` vs `Propagation(s): 127.941`.

I do not know the meaning of the 
```
Time         : 242.575s (Solving: 112.01s 1st Model: 111.15s Unsat: 0.28s)
```
line in the multi-shot setting so I cannot answer your questions. Maybe it's minima and one thread spend a lot of time waiting on the other thread. We would have to ask @BenKaufmann.

**Comment by rkaminsk** [comment]
I don't think there is a bug. Above is the solving time for the first model and propagation time includes the solving time for all models. I am going to close this.
