### ISSUE TITLE
Algorithm Improvement

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingo-dl#26]
Negative cycle checking for a list of edges is usually done one edge at a time.
This can be improved in certain cases. While updating the potential of nodes, edges can be considered that are already true (in clasp) but not yet integrated into the graph (edges that are in the list of edges pending to be propagated).
![IMG_20200302_135058_resized_20200302_023630608](https://user-images.githubusercontent.com/18141503/75681497-0068ba00-5c94-11ea-922e-5bda1cf26775.jpg)

This is true for edges that are visited but the outgoing node is not yet visited (visited time = inf).
The reason extraction also needs to be adopted to find negative cycles not containing the original edge.
In this way, both edges can be propagated at the same time with the algorithm, saving an additional call.

Observed behavior on job/flow shop problems is that usually only a few (2) edges are propagated at one, while on train scheduling benchmarks, on average 60 and in some cases over 1500 edges are propagated at once. These calls could be speed up by a factor.

**Comment by rkaminsk** [comment]
> Observed behavior on job/flow shop problems is that usually only a few (2) edges are propagated at one, while on train scheduling benchmarks, on average 60 and in some cases over 1500 edges are propagated at once. These calls could be speed up by a factor.

To really figure out if we can speed up propagation on the train scheduling benchmarks, we would have to know some more things:
1. Propagation has to dominate the overall runtime. For example, if propagation takes 50% of the total runtime, we can only speed up the system by a factor of 2 on such a benchmark.
2. Just the number of edges propagated does not indicate whether there is potential to speedup propagation. We could count how many edges were traversed more than once where we encountered the situation described above. Putting this number in relation with the total number of edges traversed should give a good idea about the potential speedups we can get.

**Comment by MaxOstrowski** [comment]
> Propagation has to dominate the overall runtime. For example, if propagation takes 50% of the total runtime, we can only speed up the system by a factor of 2 on such a benchmark.

About what propagation are we talking (inverse, partial, partial+, full). Enabling full propagation even the initial propagation on level 0 takes 30min for some benchmarks due to the sheer size of the graph.
How will this behaviour change when we add bound propagation from clingcon to it.

**Comment by MaxOstrowski** [comment]
> This is true for edges that are visited but the outgoing node is not yet visited (visited time = inf).

Would it be something like this?

```
        // detect negative cycles
        while (!costs_heap_.empty() && !u.visited_from) {
            auto s_idx = costs_heap_.pop(m);
            auto &s = nodes_[s_idx];
            assert(s.visited_from);
            s.visited_from = ++dfs;
            set_potential(s, level, s.potential() + s.cost_from);
            for (auto st_idx : s.outgoing) {
                ++stats_.propagate_cost_add;
                assert(st_idx < numeric_cast<int>(edges_.size()));
                auto &st = edges_[st_idx];
                auto &t = nodes_[st.to];
                auto c = s.potential() + st.weight - t.potential();



               /// pseudo code
               if (!t.visited_from && st_idx in state.todo_edges)
                  ++some_counter;



                if (c < (t.visited_from ? t.cost_from : 0)) {
                    assert(c < 0);
                    t.path_from = st_idx;
                    t.cost_from = c;
                    if (!t.visited_from) {
                        t.visited_from = 1;
                        visited_from_.emplace_back(st.to);
                        costs_heap_.push(m, st.to);
                    }
                    else {
                        costs_heap_.decrease(m, m.offset(st.to));
                    }
                }
            }
        }
```

I fear that this does not take into account subsequent edges that are visited during this search on this branch, but maybe this is ok.

**Comment by rkaminsk** [comment]
> > Propagation has to dominate the overall runtime. For example, if propagation takes 50% of the total runtime, we can only speed up the system by a factor of 2 on such a benchmark.
> 
> About what propagation are we talking (inverse, partial, partial+, full). Enabling full propagation even the initial propagation on level 0 takes 30min for some benchmarks due to the sheer size of the graph.
> How will this behaviour change when we add bound propagation from `clingcon` to it.

This is not what I meant. I meant the total time the propagator spends compared to the total runtime. We already have the statistics for this. I am not thinking of clingo-dl's propagation modes or extensions of them here.

**Comment by rkaminsk** [comment]
> > This is true for edges that are visited but the outgoing node is not yet visited (visited time = inf).
> 
> Would it be something like this?
> [...]
> I fear that this does not take into account subsequent edges that are visited during this search on this branch, but maybe this is ok.

This would give us an idea, if there are even situations where we can apply this (potential) optimization. Potential because I have not fully thought it through yet. Counting the number of edges that are visited more than once is also easy. Just initialize some struct at the beginning of the propagation call to keep the extra information. Keep in mind that the code for such a test does not need to be nice. It is deleted anyway and you won't hear any complaints from me (except if it is wrong). :wink:

**Comment by MaxOstrowski** [comment]
What do you think of this logging. Is this ok ?
https://github.com/potassco/clingoDL/tree/test/multiple_edge
The numbers seem to be quite high on xxx_shop and train benchmarks.
The number of Double Visited in the stats would need to be compared to Cost consistency + Edges Added.

**Comment by MaxOstrowski** [comment]
[results.zip](https://github.com/potassco/clingoDL/files/4701333/results.zip)

I added the computation of the number of edges that "unnecessarily" visited.
For some classes this is negligible, for others it is about 30%.

Propagation takes also about 30% of the solving time.

So as a rough estimate we could get at max 10% better solving time ?

PS: I found a bug in the parsing of the stats why in all previous results the propagation times had been of. We finally see some propagation time in the benchmarks.

**Comment by MaxOstrowski** [comment]
Enabling any form of real propagation (`--propagate`) will change these results. If we do not need to touch edges twice we also do not need to propagate them...

**Comment by rkaminsk** [comment]
> So as a rough estimate we could get at max 10% better solving time ?

With this it is not very motivating to start any work here. Probably we should have a look at the propagation through the zero node first.

> Enabling any form of real propagation (`--propagate`) will change these results. If we do not need to touch edges twice we also do not need to propagate them...

The full propagation has to be run for every edge. There might be cases where it can be skipped but this is not possible in general.

**Comment by MaxOstrowski** [comment]
10% doesn't sound like much,but this includes grounding etc... But 30% less propagation time sounds not that bad actually.
But I agree that bound propagation should be first.
