### ISSUE TITLE
Optimization is broken in wip

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingo-dl#47]
`ctl.add("__bound", {"s", "b"}, "&diff { s-0 } <= b.");`
uses old diff predicate. Internally we need __diff_h I think.
@rkaminsk Should we write diff_h here in the app or somehow put it through the AST converter... ?

**Comment by rkaminsk** [comment]
I would put it through the existing `Rewriter` class adding a method to load a string. I hope the one below works:
```cpp
void rewrite(char const *str) {
  CLINGO_CALL(clingo_parse_program(str, rewrite_, this, nullptr, nullptr, 0));
}
```
