### ISSUE TITLE
#include "XXX". not checking relative directory

### ISSUE THREAD

**Issue by daveraja** [potassco/clingo-dl#56]
Clingo-dl version 1.1.1 is only checking the working directory and not the relative directory. I looked through previous issues and couldn't find any reference to problem, so maybe it hasn't been fixed yet.

Say I have a directory `encoding` containing `foo.lp` and `bar.lp`:

`bar.lp` contains:
 
      barred.

`foo.lp` contains:     

      #include "bar.lp". 
      fooed.

Running from the root directory:

     clingo-dl encodings/foo.lp

gives me `error: file could not be opened: bar.lp`

With normal `clingo` it works fine:

     clingo encodings/foo.lp

**Comment by MaxOstrowski** [comment]
This is already fixed in clingo-dl 1.1.2, e.g. in the wip branch or on conda 
`conda install -c potassco/label/dev clingo-dl`
