### ISSUE TITLE
single source shortest path with clingo

### ISSUE THREAD

**Issue by Jessicaleone** [potassco/clingo-dl#70]
I'm trying to find all the shortest path from one source node to all other destination node (so 1-3,1-5,1,4) with the relative cost for each shortest path.

I've tried with this code

```
node(1..5).

edge(1,2,1).
edge(2,3,9).
edge(3,4,4).
edge(4,1,4).
edge(1,3,1).
edge(3,5,7).


start(1).
end(3).
end(4).
end(5).

0{selected(X,Y)}1:-edge(X,Y,W).
path(X,Y):-selected(X,Y).
path(X,Z):-path(X,Y),path(Y,Z).
:-start(X),end(Y),not path(X,Y).
cost(C):-C=#sum{W,X,Y:edge(X,Y,W),selected(X,Y)}.
#minimize{C:cost(C)}.

#show selected/2.
```

but my code return this answer

> `clingo version 5.6.0 (c0a2cf99)
> Reading from stdin
> Solving...
> Answer: 1
> selected(3,4) selected(1,3) selected(3,5)
> Optimization: 12
> OPTIMUM FOUND
> 
> Models       : 1
> Optimum    : yes
> Optimization : 12
> Calls        : 1
> Time         : 0.043s (Solving: 0.00s 1st Model: 0.00s Unsat: 0.00s)
> CPU Time     : 0.000s`

what is wrong? why I don't have all shortest path and the cost for each shortest path?

**Comment by rkaminsk** [comment]
Your encoding does not ensure that the selected edges form paths. It looks like you should write your encoding so that 3 separate paths from start to end are generated. Then you can minimize the costs associated with the paths to get the shortest ones. To enumerate all solutions you can use `--opt-mode=optN`.

I don't want to give a solution here because it looks a bit like this might be an assignment.

**Comment by Jessicaleone** [comment]
how can I generate 3 separated path?

**Comment by rkaminsk** [comment]
For example by including the end node as an argument in the path predicate:
```
path(End,X,Y)
```

**Comment by rkaminsk** [comment]
Your encoding should already work for a single end node (if I understand your problem description correctly). All you have to do is to generate three separate paths and minimize their costs.

**Comment by Jessicaleone** [comment]
Yes it works also with different end nodes but it doesn't show the paths separately if they have one arc in common

**Comment by rkaminsk** [comment]
You could start by adding the end point to the selected edges to generate one path per end point. All that is left to do is modify your remaing rules.
```
0{selected(E,X,Y)}1:-end(E), edge(X,Y,W).
```

**Comment by Jessicaleone** [comment]
Ok thanks, I will try but I don't know how to go ahead

**Comment by Jessicaleone** [comment]
Can you give me the solution?

**Comment by rkaminsk** [comment]
```
node(1..5).

edge(1,2,1).
edge(2,3,9).
edge(3,4,4).
edge(4,1,4).
edge(1,3,1).
edge(3,5,7).


start(1).
end(3).
end(4).
end(5).

0{selected(E,X,Y)}1:-edge(X,Y,W), end(E).
path(E,X,Y):-selected(E,X,Y).
path(E,X,Z):-path(E,X,Y),path(E,Y,Z).
:-start(X),end(Y),not path(E,X,Y).
cost(E,C):-end(E),C=#sum{W,X,Y:edge(X,Y,W),selected(E,X,Y)}.
#minimize{C,E:cost(E,C)}.

#show selected/2.
```
Note though that this is not a very efficient solution to the problem.
